backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
display_url: https://industries-soniques.netlify.app # TODO : replace for https://industries-soniques.com/ when DNS gets set up
logo_url: https://industries-soniques.netlify.app/images/logo.jpeg # TODO : replace for https://industries-soniques.com/ when DNS gets set up
collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{slug}}-{{campaign}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Client name" }
      - { label: "Campaign", name: "campaign", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Vimeo ID",
          name: "vimeo_id",
          widget: "string",
          hint: "https://vimeo.com/341455902",
        }
      - {
          label: "Video Thumbnail",
          name: "video_thumbnail",
          widget: "image",
          choose_url: false,
        }
      - { label: "Format", name: "format", widget: "string", required: false }
      - {
          label: "Director",
          name: "director",
          widget: "string",
          required: false,
        }
      - label: "Music, Sound Design & Mix"
        name: "music"
        widget: "select"
        multiple: true
        options: ["Sau Poler (Indústries Sòniques)"]
        default: ["Sau Poler (Indústries Sòniques)"]
      - { label: "Body", name: "body", widget: "markdown", required: false }
